package main

import (
	"fmt"
	"os"
)

func HandleError(err error) {
	if err != nil {
		panic(err)
	}
}
func main() {
	file01, err := os.OpenFile("D:\\TryDir\\Try01.txt", os.O_CREATE|os.O_WRONLY, os.ModePerm)
	HandleError(err)
	defer file01.Close()
	RL := []byte("There is a reason")
	HL := []byte{0, 65, 66, 67, 68, 69}
	n, err := file01.Write(RL)
	HandleError(err)
	fmt.Println("成功写出：", n)
	n, err = file01.Write(HL)
	HandleError(err)
	fmt.Println("成功写出：", n)
}
